### ISSUE TITLE
Set title on PDFs

### ISSUE THREAD

**Issue by TheDanMiller** [CMSgov/macpro-platform-doc-conversion#48]
## Type of Issue:

- [x] Enhancement: New feature or request

#### Issue Creator Checklist

- [x] This issue has been thoroughly documented below; a developer should be able to understand the issue by reading it.

## Background

CARTS is sending HTML to doc-conversion and the PDF that came back was examined for 508 compliance. One of the failing items is that the title of the document is not being set. 

## Proposed Approach

Pull the title from the HTML document and use that to set the title of the PDF.  
Not sure how to handle no title being sent over

## Value

Moves us closer to 508 compliant documents

## AC:

Documents that are created using the service have a title set [https://helpx.adobe.com/acrobat/using/create-verify-pdf-accessibility.html?trackingid=KACNN#DocTitle](https://helpx.adobe.com/acrobat/using/create-verify-pdf-accessibility.html?trackingid=KACNN#DocTitle)

**Comment by kenrickveit** [comment]
We can handle this with `--pdf-title=TITLE` 
https://www.princexml.com/doc/command-line/#utility-options

We'll need to add an optional arg users can pass for this.

**Comment by kenrickveit** [comment]
Opened an internal Jira on this. Found that the `title` functionality already works if it is set as a tag in the supplied HTML.
Added a note about this at the top of the README for inputs. 
Marking this closed, can re-open if there are cases where the tagging doesn't work and we have to set it with Prince args.
