### ISSUE TITLE
Set PDF Language

### ISSUE THREAD

**Issue by TheDanMiller** [CMSgov/macpro-platform-doc-conversion#49]
## Type of Issue:

- [x] Enhancement: New feature or request

#### Issue Creator Checklist

- [x] This issue has been thoroughly documented below; a developer should be able to understand the issue by reading it.

## Background

CARTS is sending HTML to doc-conversion and the PDF that came back was examined for 508 compliance. One of the failing items is that the language of the document is not being set. 

## Proposed Approach

Pull the language from the HTML document and use that to set the title of the PDF.  
Default to English when no language is sent

## Value

Moves us closer to 508 compliant documents

## AC:

Documents that are created using the service have a language set [https://helpx.adobe.com/acrobat/using/create-verify-pdf-accessibility.html?trackingid=KACNN#PrimeLang](https://helpx.adobe.com/acrobat/using/create-verify-pdf-accessibility.html?trackingid=KACNN#PrimeLang)

**Comment by kenrickveit** [comment]
We can handle this with: 
`--pdf-lang=LANG`

https://www.princexml.com/doc/command-line/#utility-options

**Comment by kenrickveit** [comment]
Opened an internal Jira on this. Found that the `lang` functionality already works if it is set as a tag in the supplied HTML.
Added a note about this at the top of the README for inputs. 
Marking this closed, can re-open if there are cases where the tagging doesn't work and we have to set it with Prince args.
